joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: bumperbot_controller/cmd_vel
      deadman_buttons: [5]  # RB acts like PS4 R1
      axis_mappings:
        twist-linear-x:
          axis: 1     # Left stick vertical
          scale: 1.0
          offset: 0.0
        twist-angular-z:
          axis: 0     # Left stick horizontal
          scale: 3.0
          offset: 0.0