joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: robovacuum_controller/cmd_vel
      deadman_buttons: [5]  
      axis_mappings:
        twist-linear-x:
          axis: 0     # Left stick vertical
          scale: 2.0
          offset: 0.0
        twist-angular-z:
          axis: 3     # right stick horizontal
          scale: 2.0
          offset: 0.0
